# Generated by Django 4.2.6 on 2024-01-11 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('bank_account', '0002_alter_bankaccount_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('associated_bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_account.bankaccount')),
                ('associated_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.role')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
