# Generated by Django 4.2.6 on 2024-01-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_fibrebale_added_by_alter_ropebundle_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropebundle',
            old_name='size_in_mms',
            new_name='size',
        ),
    ]
