# Generated by Django 4.2.6 on 2024-01-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='access_to_warehouse_management',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
